-- 定时任务日志表
CREATE TABLE IF NOT EXISTS schedule_job_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    job_name VARCHAR(100) NOT NULL COMMENT '任务名称',
    job_handler VARCHAR(100) NOT NULL COMMENT '任务处理器',
    job_param VARCHAR(500) DEFAULT NULL COMMENT '任务参数',
    job_id VARCHAR(100) DEFAULT NULL COMMENT '任务ID(XXL-Job)',
    status TINYINT DEFAULT 1 COMMENT '执行状态：1-成功，0-失败',
    execute_result TEXT DEFAULT NULL COMMENT '执行结果',
    execute_time DATETIME DEFAULT NULL COMMENT '执行时间',
    duration BIGINT DEFAULT NULL COMMENT '执行耗时(ms)',
    error_message TEXT DEFAULT NULL COMMENT '错误信息',
    shard_index INT DEFAULT 0 COMMENT '分片索引',
    shard_total INT DEFAULT 1 COMMENT '分片总数',
    executor_address VARCHAR(255) DEFAULT NULL COMMENT '执行器地址',
    retry_count INT DEFAULT 0 COMMENT '重试次数',
    alert_status TINYINT DEFAULT 0 COMMENT '告警状态：0-未告警，1-已告警，2-告警失败',
    alert_message TEXT DEFAULT NULL COMMENT '告警信息',
    alert_time DATETIME DEFAULT NULL COMMENT '告警时间',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_job_handler (job_handler),
    INDEX idx_execute_time (execute_time),
    INDEX idx_status (status),
    INDEX idx_shard (shard_index, shard_total)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务执行日志表';

-- 订单归档表
CREATE TABLE IF NOT EXISTS order_archive (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    order_no VARCHAR(32) NOT NULL COMMENT '订单编号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    total_amount DECIMAL(10,2) DEFAULT NULL COMMENT '订单总金额',
    pay_amount DECIMAL(10,2) DEFAULT NULL COMMENT '支付金额',
    freight_amount DECIMAL(10,2) DEFAULT NULL COMMENT '运费金额',
    discount_amount DECIMAL(10,2) DEFAULT NULL COMMENT '优惠金额',
    order_status TINYINT DEFAULT NULL COMMENT '订单状态',
    pay_status TINYINT DEFAULT NULL COMMENT '支付状态',
    receiver_name VARCHAR(50) DEFAULT NULL COMMENT '收货人姓名',
    receiver_phone VARCHAR(20) DEFAULT NULL COMMENT '收货人电话',
    receiver_address VARCHAR(200) DEFAULT NULL COMMENT '收货人地址',
    remark VARCHAR(500) DEFAULT NULL COMMENT '订单备注',
    pay_time DATETIME DEFAULT NULL COMMENT '支付时间',
    ship_time DATETIME DEFAULT NULL COMMENT '发货时间',
    finish_time DATETIME DEFAULT NULL COMMENT '完成时间',
    cancel_time DATETIME DEFAULT NULL COMMENT '取消时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    archive_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '归档时间',
    archive_batch VARCHAR(50) DEFAULT NULL COMMENT '归档批次号',
    UNIQUE KEY uk_order_no (order_no),
    INDEX idx_user_id (user_id),
    INDEX idx_archive_batch (archive_batch),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单归档表';
